"""remove bio

Revision ID: c5450ead2dec
Revises: 65f34baf7890
Create Date: 2025-03-02 22:44:05.016678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5450ead2dec'
down_revision = '65f34baf7890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(length=256), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
